### ISSUE TITLE
AutoRefreshSession and incorrect client's time issue

### ISSUE THREAD

**Issue by AntonPetrov83** [heroiclabs/nakama-dotnet#159]
I was looking into Nakama sources to get the idea of how it implements session refreshing because I have issues in my game (not using Nakama).

And I am pretty sure you will have mine problems too:
1. If the user's clock is ahead of time then you will end up refreshing token every call.
2. If the user's clock is behind some value then your token will never be refreshed.

**Comment by novabyte** [comment]
@AntonPetrov83 We've considered this one but for (1) and (2) we don't consider it an issue because a clock manipulation hacks by a player is one that is done with intent. If you're concerned with whether bad actors can still play your game when they cheat the game I suggest you use a server REST API call to get the current server time as the time source. 

Keep in mind this will require that the game has at least enough connectivity to reach the server once at the start of each play session.
