### ISSUE TITLE
Configurable size on MaxMessageSize in WebSocketAdapter.cs

### ISSUE THREAD

**Issue by samuelpereira** [heroiclabs/nakama-dotnet#31]
Hi,

Can you make the MaxMessageSize configurable ? 
Because the limit of MaxMessageSize = 1024 * 256 is too low!

Thanks

**Comment by cata0309** [comment]
Please do! This affects my project as well

**Comment by novabyte** [comment]
@cata0309 How large are the messages you want to send? It's very unusual (we've never encountered this yet with a game project) which needs to send more than ~256KB in a single message.

**Comment by kstewart-zynga** [comment]
We are seeing this as well when sending over some configuration data. We're at the point in the project where it isn't easy to reeingineer the data we return to be more broken up (possible long term goal), so having this be configurable would save us some medium term headaches.

Also note that because this is serialized into a JSON envelope by protobuf if you're serializing especially deeply nested objects then escaping the json can actually add quite a bit of overhead (we're seeing 15%), so the ability to configure this would greatly assist in the dev process.

**Comment by novabyte** [comment]
This is now resolved and will be part of the next release.
